name: Auto-Deploy to Dokku

on:
  push:
    branches:
      - main
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Deploy to Dokku
        uses: dokku/github-action@v1.4.0
        with:
          git_remote_url: ${{ github.ref_name == 'prod' && 'ssh://dokku@69.164.247.195:22/my-app-prod' || 'ssh://dokku@69.164.247.195:22/my-app-staging' }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          branch: ${{ github.ref_name }}
